services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
    expose:
      - "80"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot-conf/etc:/etc/letsencrypt
      - ./nginx/certbot-conf/lib:/var/lib/letsencrypt
      - ./frontend/dist:/usr/share/nginx/html
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /usr/share/nginx/html; done;"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
