services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: []

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: npm start
