services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./database:/var/www/html/database
    ports:
      - "9000:9000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
