name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images locally (optional)
        run: |
          docker compose -f docker-compose.yml build

      - name: Deploy to VPS and renew certbot
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "\
            cd /var/www/portfolio && \
            sudo git fetch origin && \
            sudo git reset --hard origin/main && \
            sudo git pull origin main && \
            sudo docker-compose -f docker-compose.yml up --build -d && \
            sudo docker run --rm \
              -v /var/www/portfolio/nginx/certbot-conf/etc:/etc/letsencrypt \
              -v /var/www/portfolio/nginx/certbot-conf/lib:/var/lib/letsencrypt \
              -v /var/www/portfolio/frontend/dist:/usr/share/nginx/html \
              certbot/certbot renew --quiet --deploy-hook \"sudo docker-compose -f docker-compose.yml restart frontend\""
